name: PR Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: 'Install Node'
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Chrome extension
        run: pnpm run build

      - name: Build Firefox extension
        run: pnpm run build:firefox

      - name: Upload Chrome build
        uses: actions/upload-artifact@v4
        with:
          name: chrome-pr-${{ github.event.pull_request.number }}
          path: .output/chrome-mv3/
          retention-days: 14

      - name: Upload Firefox build
        uses: actions/upload-artifact@v4
        with:
          name: firefox-pr-${{ github.event.pull_request.number }}
          path: .output/firefox-mv2/
          retention-days: 14
